### ISSUE TITLE
Support 24 hour time format in annotation chart.

### ISSUE THREAD

**Issue by kmpm** [urbiworx/node-red-contrib-googlechart#3]
Not everyone uses 12 hour time format and a checkbox in chart request or detecting the browser time format at runtime would be nice.

How to change format at all...
http://stackoverflow.com/questions/18639517/change-to-a-24-hour-format-for-datetime-data-in-google-charts

**Comment by urbiworx** [comment]
You can now give a formatter string starting with version 0.0.8.
