### ISSUE TITLE
Display dynamic data

### ISSUE THREAD

**Issue by natcl** [urbiworx/node-red-contrib-googlechart#4]
Would there be a way to display dynamic charts ?
This would be very useful to display data from sensors in realtime...

I did it (in a web.py project) by calling setInterval for the drawChart method:
https://github.com/natcl/brams-atmo/blob/master/templates/index.html

**Comment by urbiworx** [comment]
I believe what you mean by dynamic is already implemented, all charts (besides the annotation chart) reload after one minute;
((that.charttype!=="AnnotationChart")?'setTimeout(function () { drawChart(); }, 60000);

**Comment by natcl** [comment]
Oh I see,
Would there be a way to expose the timeout via node red's gui ?

I'm not sure it would solve the problem of refreshing the data source though...


--
lecaude.com 
studioimaginaire.com

**Comment by urbiworx** [comment]
Yes that would be perfectly possible to expose this setting. 
Regarding the data source it should already work - the node that is attached to the google chart will be evaluated every 60 seconds - so if you have for example a monogdb node attached (like me) then the data from mongodb is pulled automatically every 60 seconds. That is, only for Charts that are not the Annotation Chart.

**Comment by natcl** [comment]
That's great !
Then just an option to set the refresh timeout would do the trick !

**Comment by natcl** [comment]
I was also wondering, would the gauge chart work ?

**Comment by urbiworx** [comment]
Is editable now. For gauge please see https://github.com/urbiworx/node-red-contrib-freeboard , might better suit your need.

**Comment by natcl** [comment]
Thanks!

freeboard looks very nice, will give it a try !


--
lecaude.com 
studioimaginaire.com
